# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmap.proto\x12\tbox.world\"\x0f\n\rGetMapRequest\"\x10\n\x0eGetMapResponse2C\n\x03Map\x12<\n\x03Get\x12\x18.box.world.GetMapRequest\x1a\x19.box.world.GetMapResponse\"\x00\x42\x16Z\x14./go/box/world;worldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024./go/box/world;world'
  _globals['_GETMAPREQUEST']._serialized_start=24
  _globals['_GETMAPREQUEST']._serialized_end=39
  _globals['_GETMAPRESPONSE']._serialized_start=41
  _globals['_GETMAPRESPONSE']._serialized_end=57
  _globals['_MAP']._serialized_start=59
  _globals['_MAP']._serialized_end=126
# @@protoc_insertion_point(module_scope)
