# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: region.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregion.proto\x12\tbox.world\"&\n\nregionBase\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x13\n\x11ListRegionRequest\"<\n\x12ListRegionResponse\x12&\n\x07regions\x18\x01 \x03(\x0b\x32\x15.box.world.regionBase\"\x1e\n\x10GetRegionRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x11GetRegionResponse\x12%\n\x06region\x18\x01 \x01(\x0b\x32\x15.box.world.regionBase2\x93\x01\n\x06Region\x12\x45\n\x04List\x12\x1c.box.world.ListRegionRequest\x1a\x1d.box.world.ListRegionResponse\"\x00\x12\x42\n\x03Get\x12\x1b.box.world.GetRegionRequest\x1a\x1c.box.world.GetRegionResponse\"\x00\x42\x16Z\x14./go/box/world;worldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'region_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024./go/box/world;world'
  _globals['_REGIONBASE']._serialized_start=27
  _globals['_REGIONBASE']._serialized_end=65
  _globals['_LISTREGIONREQUEST']._serialized_start=67
  _globals['_LISTREGIONREQUEST']._serialized_end=86
  _globals['_LISTREGIONRESPONSE']._serialized_start=88
  _globals['_LISTREGIONRESPONSE']._serialized_end=148
  _globals['_GETREGIONREQUEST']._serialized_start=150
  _globals['_GETREGIONREQUEST']._serialized_end=180
  _globals['_GETREGIONRESPONSE']._serialized_start=182
  _globals['_GETREGIONRESPONSE']._serialized_end=240
  _globals['_REGION']._serialized_start=243
  _globals['_REGION']._serialized_end=390
# @@protoc_insertion_point(module_scope)
