# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import general_pb2 as general__pb2


class GeneralStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDB = channel.unary_unary(
                '/box.General/InitDB',
                request_serializer=general__pb2.InitDBRequest.SerializeToString,
                response_deserializer=general__pb2.InitDBResponse.FromString,
                )


class GeneralServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneralServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDB': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDB,
                    request_deserializer=general__pb2.InitDBRequest.FromString,
                    response_serializer=general__pb2.InitDBResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'box.General', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class General(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/box.General/InitDB',
            general__pb2.InitDBRequest.SerializeToString,
            general__pb2.InitDBResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
