# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneral.proto\x12\x03\x62ox\"\x0f\n\rInitDBRequest\"%\n\x0eInitDBResponse\x12\x13\n\x0binitialized\x18\x01 \x01(\x08\x32>\n\x07General\x12\x33\n\x06InitDB\x12\x12.box.InitDBRequest\x1a\x13.box.InitDBResponse\"\x00\x42\x0eZ\x0c./go/box;boxb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'general_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./go/box;box'
  _globals['_INITDBREQUEST']._serialized_start=22
  _globals['_INITDBREQUEST']._serialized_end=37
  _globals['_INITDBRESPONSE']._serialized_start=39
  _globals['_INITDBRESPONSE']._serialized_end=76
  _globals['_GENERAL']._serialized_start=78
  _globals['_GENERAL']._serialized_end=140
# @@protoc_insertion_point(module_scope)
