# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tenant.proto for package 'box.tenant'

require 'grpc'
require 'tenant_pb'

module Box
  module Tenant
    module Tenant
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'box.tenant.Tenant'

        rpc :Get, ::Box::Tenant::GetTenantRequest, ::Box::Tenant::GetTenantResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
