# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenant.proto

require 'google/protobuf'


descriptor_data = "\n\x0ctenant.proto\x12\nbox.tenant\"\x12\n\x10GetTenantRequest\"\x13\n\x11GetTenantResponse2N\n\x06Tenant\x12\x44\n\x03Get\x12\x1c.box.tenant.GetTenantRequest\x1a\x1d.box.tenant.GetTenantResponse\"\x00\x42\x18Z\x16./go/box/tenant;tenantb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Box
  module Tenant
    GetTenantRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.tenant.GetTenantRequest").msgclass
    GetTenantResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.tenant.GetTenantResponse").msgclass
  end
end
