# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x0b\x62ox.account\"\x13\n\x11GetAccountRequest\"\x14\n\x12GetAccountResponse2S\n\x07\x41\x63\x63ount\x12H\n\x03Get\x12\x1e.box.account.GetAccountRequest\x1a\x1f.box.account.GetAccountResponse\"\x00\x42\x1aZ\x18./go/box/account;accountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030./go/box/account;account'
  _globals['_GETACCOUNTREQUEST']._serialized_start=30
  _globals['_GETACCOUNTREQUEST']._serialized_end=49
  _globals['_GETACCOUNTRESPONSE']._serialized_start=51
  _globals['_GETACCOUNTRESPONSE']._serialized_end=71
  _globals['_ACCOUNT']._serialized_start=73
  _globals['_ACCOUNT']._serialized_end=156
# @@protoc_insertion_point(module_scope)
