# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: account.proto for package 'box.account'

require 'grpc'
require 'account_pb'

module Box
  module Account
    module Account
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'box.account.Account'

        rpc :Get, ::Box::Account::GetAccountRequest, ::Box::Account::GetAccountResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
