# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

require 'google/protobuf'


descriptor_data = "\n\raccount.proto\x12\x0b\x62ox.account\"\x13\n\x11GetAccountRequest\"\x14\n\x12GetAccountResponse2S\n\x07\x41\x63\x63ount\x12H\n\x03Get\x12\x1e.box.account.GetAccountRequest\x1a\x1f.box.account.GetAccountResponse\"\x00\x42\x1aZ\x18./go/box/account;accountb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Box
  module Account
    GetAccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.account.GetAccountRequest").msgclass
    GetAccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.account.GetAccountResponse").msgclass
  end
end
