# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenant.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctenant.proto\x12\nbox.tenant\"\x12\n\x10GetTenantRequest\"\x13\n\x11GetTenantResponse2N\n\x06Tenant\x12\x44\n\x03Get\x12\x1c.box.tenant.GetTenantRequest\x1a\x1d.box.tenant.GetTenantResponse\"\x00\x42\x18Z\x16./go/box/tenant;tenantb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026./go/box/tenant;tenant'
  _globals['_GETTENANTREQUEST']._serialized_start=28
  _globals['_GETTENANTREQUEST']._serialized_end=46
  _globals['_GETTENANTRESPONSE']._serialized_start=48
  _globals['_GETTENANTRESPONSE']._serialized_end=67
  _globals['_TENANT']._serialized_start=69
  _globals['_TENANT']._serialized_end=147
# @@protoc_insertion_point(module_scope)
