# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto

require 'google/protobuf'


descriptor_data = "\n\rgeneral.proto\x12\x03\x62ox\"\x0f\n\rInitDBRequest\"%\n\x0eInitDBResponse\x12\x13\n\x0binitialized\x18\x01 \x01(\x08\x32>\n\x07General\x12\x33\n\x06InitDB\x12\x12.box.InitDBRequest\x1a\x13.box.InitDBResponse\"\x00\x42\x0eZ\x0c./go/box;boxb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Box
  InitDBRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.InitDBRequest").msgclass
  InitDBResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.InitDBResponse").msgclass
end
