# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: general.proto for package 'box'

require 'grpc'
require 'general_pb'

module Box
  module General
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'box.General'

      rpc :InitDB, ::Box::InitDBRequest, ::Box::InitDBResponse
    end

    Stub = Service.rpc_stub_class
  end
end
