# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: map.proto for package 'box.world'

require 'grpc'
require 'map_pb'

module Box
  module World
    module Map
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'box.world.Map'

        rpc :Get, ::Box::World::GetMapRequest, ::Box::World::GetMapResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
