# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: region.proto

require 'google/protobuf'


descriptor_data = "\n\x0cregion.proto\x12\tbox.world\"&\n\nregionBase\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x13\n\x11ListRegionRequest\"<\n\x12ListRegionResponse\x12&\n\x07regions\x18\x01 \x03(\x0b\x32\x15.box.world.regionBase\"\x1e\n\x10GetRegionRequest\x12\n\n\x02id\x18\x01 \x01(\t\":\n\x11GetRegionResponse\x12%\n\x06region\x18\x01 \x01(\x0b\x32\x15.box.world.regionBase2\x93\x01\n\x06Region\x12\x45\n\x04List\x12\x1c.box.world.ListRegionRequest\x1a\x1d.box.world.ListRegionResponse\"\x00\x12\x42\n\x03Get\x12\x1b.box.world.GetRegionRequest\x1a\x1c.box.world.GetRegionResponse\"\x00\x42\x16Z\x14./go/box/world;worldb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Box
  module World
    RegionBase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.world.regionBase").msgclass
    ListRegionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.world.ListRegionRequest").msgclass
    ListRegionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.world.ListRegionResponse").msgclass
    GetRegionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.world.GetRegionRequest").msgclass
    GetRegionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("box.world.GetRegionResponse").msgclass
  end
end
