# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: region.proto for package 'box.world'

require 'grpc'
require 'region_pb'

module Box
  module World
    module Region
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'box.world.Region'

        rpc :List, ::Box::World::ListRegionRequest, ::Box::World::ListRegionResponse
        rpc :Get, ::Box::World::GetRegionRequest, ::Box::World::GetRegionResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
